- __tests__/full-setup.test.js
- mocks/firestore.js
- Adds `mockCollectionGroup` as a mocked function in `firestore.js`
- Adds tests in `full-setup.test.js`
https://github.com/Upstatement/firestore-jest-mock/issues/10
Make sure the tests pass
> Add collectionGroup as a mocked function

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/question.md
This PR updates the contributing documentation and GitHub issue templates to use the correct information about `firestore-jest-mock`.
> Updating docs to include correct repo info

- __tests__/mock-firestore.test.js
- mocks/firestore.js
Updates doc function to account of collection path and write tests to account for that case
Fixes #14 
In your repo run `db.doc('foo/bar/id')` and assert that it works as intended.
> Update doc function to account for collection path

- mocks/firebase.js
In our project, we use only `firebase-admin` package and there is no `firebase` module imported.
When I attempt to mock `firestore` in such scenario, it fails (`Cannot find module 'firebase' from 'node_modules/firestore-jest-mock/mocks/firebase.js'`). That's because jest can not find `firebase` module in this line: `jest.doMock('firebase', () => firebaseStub(overrides));`
This change applies mocking only if a respective module can be found as a dependency. `require.resolve()` was the best way I found to check if a package can be found, but it throws an exception if a module was not found - therefore the empty `catch`.
In addition, I changed the usage of the `mock` functions to `doMock` - when plain mocking was replaced with the function call the `&&` trick did not work anymore and …
> Fix jest error on missing dependencies

- README.md
- __tests__/mock-fieldvalue.test.js
- mocks/firebase.js
- mocks/firestore.js
- package.json
Added a `firestore.FieldValue` mock to `FakeFirestore`. An instance of this new `FakeFirestore.FieldValue` class is normally created by calling one of its static functions: `arrayUnion`, `arrayRemove`, `increment`, `serverTimestamp`, and `delete`. These each should correspond to Firebase Firestore's own [`FieldValue` API](https://firebase.google.com/docs/reference/js/firebase.firestore.FieldValue).
Each `FakeFirestore.FieldValue` instance represents a sentinel that contains information on how to transform arbitrary values. If we so choose, we may modify `set`, `update`, and `add` to actively transform mock data using these sentinels.
The new `FakeFirestore.FieldValue` class can return transformed versions of arbitrary values by passing the value to its `transform` function.
Fixes #23 
Run …
> Add FakeFirestore.FieldValue

- mocks/firebase.js
Fixes `console.info` introduced by me in https://github.com/Upstatement/firestore-jest-mock/pull/28 - 
it should use template string.
Related to PR https://github.com/Upstatement/firestore-jest-mock/pull/28
> Fix console.info - use template string

- README.md
- __tests__/query.test.js
- mocks/firestore.js
- Adds mockCollectionGroup as a mocked function in firestore.js
- Fix mockLimit export that was missing
- Adds tests in query.test.js
Run test for query.test.js
> Add offset as a mock function

- README.md
This updates the example we have in our library around testing the `mockWhere` function.  This is the first example in the README, so it should be as easy to read as possible.  The current version has a `_collections` key, but since this example doesn't test subcollection, I feel it shouldn't be included.
Does the example make sense?
> update simple query example

- mocks/firestore.js
1. Allow calling `settings()`:
```ts
export const db = admin.firestore();
db.settings({ ignoreUndefinedProperties: true });
```
2. Support collection/doc path names with leading slash (e.g., '/users/aUser' vs 'users/aUser') which are supported by firestore
> Settings and path split

- __tests__/full-setup.test.js
- mocks/firestore.js
- mocks/helpers/buildDocFromHash.js
- mocks/helpers/buildQuerySnapShot.js
- mocks/query.js
Adds mock functionality for listening to snapshot changes, as documented here:
https://firebase.google.com/docs/firestore/query-data/listen
This is a harder one to *truly* mock as it adds an observer to an outside service, which we can't really mock with a simple POJO.  Instead, this is meant to stupidly imitate a user's implementation so their tests don't get hung up on this unknown method.  A future update might add an observer class, so you can manually trigger these callbacks, but that gets into the territory of "too much logic for a stub."
Fixes https://github.com/Upstatement/firestore-jest-mock/issues/63
Conversation in there as to some of the complications and the underlying API's
Taken examples from the documentation: https://firebase.google.com/docs/firestore/query-data/listen …
> add onSnapshot method for queries and doc requests

- __tests__/mock-firestore.test.js
- mocks/helpers/buildDocFromHash.js
(cherry picked from commit 8e5bb8b504962e5495675c50280e93aa90a43c40)
adds `get` function to the fake DocumentSnapshot, compatible with Firestore
The following code threw an exception:
```
const allDocs = await collection.get();
allDocs.docs.map(async (d) => {
const path = d.get('ref'); // get is not implemented
```
Unit test included
Side note: apologies for the white-space noise, somehow the linting must have gotten confused.  Hopefully not conflicts because of this...
> adding get function to fake document snapshot

- README.md
- __tests__/auth.test.js
- mocks/auth.js
Adds support for auth `signOut`
```js
​import​ ​{​ ​mockSignOut​ ​}​ ​from​ ​'firestore-jest-mock/mocks/auth'​;
it('signs out',  async () => {
const firebase = require('firebase');
const auth = firebase.auth();
await auth.signOut();
expect(mockSignOut).toHaveBeenCalled():
});
```
> feat: support auth signOut

- README.md
- __tests__/full-setup-google-cloud-firestore.test.js
- index.js
- mocks/googleCloudFirestore.js
Add support for `@google-cloud/firestore` mocking. Expose `mockGoogleCloudFirestore` as `mockFirebase`. 
Adresses https://github.com/Upstatement/firestore-jest-mock/issues/71
1. Get a project that use `@google-cloud/firestore` 
2. checkout https://github.com/CorentinDoue/firestore-jest-mock/tree/feat/support-google-cloud-firestore
3. link `firestore-jest-mock` to your project
4. write one test
> feat: support @google-cloud/firestore

- README.md
- __tests__/auth.test.js
- __tests__/full-setup.test.js
- mocks/auth.js
- mocks/firestore.js
Add support for auth and firestore's `useEmulator` with `mockUseEmulator` exported from both
```js
​import​ ​{​ ​mockUseEmulator​ ​}​ ​from​ ​'firestore-jest-mock/mocks/auth'​;
it('uses auth emulator',  () => {
const firebase = require('firebase');
const auth = firebase.auth();
auth.useEmulator('http://localhost:9099');
expect(mockUseEmulator).toHaveBeenCalledWith('http://localhost:9099'):
});
```
```js
​import​ ​{​ ​mockUseEmulator​ ​}​ ​from​ ​'firestore-jest-mock/mocks/firestore'​;
it('uses firestore emulator',  () => {
const firebase = require('firebase');
const db = firebase.firestore();
db.useEmulator('localhost', 9000);
expect(mockUseEmulator).toHaveBeenCalledWith('localhost', 9000):
});
```
> feat: support auth and firestore useEmulator

- README.md
- __tests__/full-setup.test.js
- __tests__/query.test.js
- mocks/firestore.js
- mocks/query.js
Initial work for adding support for withConverter, issue created with discussion needed
#77 
```
firestore.doc('data/1').withConverter()
firestore.collection('data').withConverter()
firestore.collection('data').doc('1').withConverter()
```
Using these calls should not throw error with function not found
> Feat/support withConverter

- __tests__/full-setup.test.js
- mocks/firestore.js
As documented here: https://googleapis.dev/nodejs/firestore/latest/WriteBatch.html#commit
The promise return by `commit` for batches resolves to an array. We don't have to reproduce the full behavior, but we should at least return the correct type
Fixes https://github.com/Upstatement/firestore-jest-mock/issues/80
> return array from commit promise

- .eslintrc
- .vscode/settings.json
- @types/global.d.ts
- index.d.ts
- mocks/firebase.d.ts
- package-lock.json
- package.json
- tsconfig.json
This PR represents some initial work on exporting type information to users. More pull requests will follow with typings for each of our exported modules.
Related to #20 
1. Create a new local project: `npm init`
2. Install the package via this branch: `npm install --save-dev https://github.com/AverageHelper/firestore-jest-mock.git#typescript-shim`
3. Add a line to index.js to require `firestore-jest-mock`:
```JavaScript
const { mockFirebase } = require("firestore-jest-mock");
```
4. Hover over `mockFirebase` to ensure that your editor picks up the type declarations:
> Add basic typing declarations

- README.md
- __tests__/full-setup.test.js
- __tests__/options.test.js
- mocks/firebase.d.ts
- mocks/firebase.js
- mocks/firestore.js
- mocks/googleCloudFirestore.js
- mocks/helpers/buildDocFromHash.js
- mocks/helpers/defaultMockOptions.js
Adds the ability to pass options to the mock, allowing you to include id's in your document's data.
Fixes: https://github.com/Upstatement/firestore-jest-mock/issues/68
Also adds the ability for future options, which I think can be a good stop-gap for https://github.com/Upstatement/firestore-jest-mock/pull/70
Pass a second param to `mockFirebase` as your "options."
You can set `includeIdsInData` to have `doc.data()` return the id of the document (custom behavior).
> add options hash to mock

- __tests__/transaction.test.js
- mocks/transaction.js
Adds the `create` method a firestore transaction, as documented here:
https://googleapis.dev/nodejs/firestore/latest/Transaction.html#create-examples
Fixes https://github.com/Upstatement/firestore-jest-mock/issues/84
Can you run a transaction with the `create` method and assert it was called?
> add transaction create method

- __tests__/full-setup-google-cloud-firestore.test.js
- __tests__/full-setup.test.js
- mocks/helpers/buildQuerySnapShot.js
`docChanges` returns an array, rather than an object with a `forEach` (like a document) as listed here:
https://firebase.google.com/docs/reference/js/firebase.firestore.QuerySnapshot#docchanges
This PR changes it to return just an empty array for now.
Fixes https://github.com/Upstatement/firestore-jest-mock/issues/89
Write an assertion that assumes the value from `docChanges` is an array
> docChanges returns an array

- mocks/fieldValue.d.ts
- mocks/firebase.d.ts
- mocks/helpers/buildDocFromHash.d.ts
- mocks/helpers/buildQuerySnapShot.d.ts
- mocks/helpers/buildQuerySnapShot.js
- mocks/helpers/defaultMockOptions.d.ts
- mocks/query.d.ts
- mocks/timestamp.d.ts
- mocks/transaction.d.ts
More TypeScript typings. This branch adds typings to more of our internal modules. What I'm looking for here is a confirmation that the type declarations presented here are where we wanna go in the future.
My next PR would add typings to the rest of the app, which should expose all relevant mock functions to TypeScript.
There is nothing yet to test. All changes are additive to internal type files.
> Add types to supporting files

- README.md
- mocks/helpers/defaultMockOptions.js
In preparation for https://github.com/Upstatement/firestore-jest-mock/pull/70, this PR adds a new option to our `mockFirebase` option.
If users want their mocked database to update during their tests, they can set this flag.  This also updates the README to spell out why it defaults to `false` and explain the downside of mutating your test stub.
Just adds the options for use in another PR.
> add mutable option

- index.d.ts
Installed this library on a TypeScript project today and when importing mockGoogleCloudFirestore I got a TS error explaining that the module does not have an exported member with that name. This PR adds it to the index.d.ts file.
> fix: export mockGoogleCloudFirestore on type def

- __tests__/auth.test.js
- mocks/auth.js
I noticed that I get the `Maximum call stack size exceeded` error when I call `currentUser` in `firebase.auth()` overwritten by `mockFirebase`.  The reason for this is simple: the `FakeAuth.currentUser()` function is being called recursively inside of it. `FakeAuth` stores the `currentUser` passed to the constructor as `currentUserRecord` object, so the problem can be solved by using the `currentUserRecord` .
I added two commits. The first commit is just a test case, and you can see that it raises the `Maximum call stack size exceeded` error. The second commit fixes it.
Simply define `mockFirebase` and call `firebase.auth().currentUser` .
> Fix Maximum call stack size exceeded in calling `firebase.auth().currentUser`

- __tests__/query.test.js
- mocks/firestore.js
- mocks/helpers/buildQuerySnapShot.js
Sorry, I kind of messed up the branches, this PR contains 2 small fixes.
Currently filtering Timestamps does not work at all because they are compared as strings, this pr adds support for comparing with Date objects.
getAll also accepts an object containing options, see https://googleapis.dev/nodejs/firestore/latest/Transaction.html#getAll. Currently, this breaks the mock as it is treated as a doc.
> Support Timestamps in where queries + ReadOptions for getAll

- __tests__/full-setup-google-cloud-firestore.test.js
- __tests__/full-setup.test.js
- mocks/firebase.js
- mocks/firestore.js
Implementation of listCollections method (see https://googleapis.dev/nodejs/firestore/latest/DocumentReference.html#listCollections) for Cloud Firestore.
None.
Tests included.
> Add listCollections method to DocumentReference

- README.md
Fixes @google-cloud/firestore documentation example to include correct expect assertion.
Fixes #112
> fix: update expect assertion on @google-cloud/firestore test example

- README.md
README was incorrect for `@react-native-firebase/firestore` compatibility, as it was using `mockGoogleCloudFirestore` instead of 
`mockReactNativeFirestore` and the example test was not passing also. 
Tested with `@react-native-firebase/firestore` version `15.3.0`
> Corrects README for React Native

- __tests__/full-setup-library-firestore.test.js
- __tests__/full-setup.test.js
- src/mocks/firestore.d.ts
- src/mocks/firestore.js
[recursiveDelete docs](https://googleapis.dev/nodejs/firestore/latest/Firestore.html#recursiveDelete)
[batch.create docs](https://googleapis.dev/nodejs/firestore/latest/WriteBatch.html#create)
Tests included.
> Add recursiveDelete & batch.create mocks

- __tests__/full-setup-library-firestore.test.js
- __tests__/full-setup.test.js
- src/mocks/firestore.d.ts
- src/mocks/query.d.ts
- src/mocks/query.js
Mock the unsubscribe callback returned by `onSnapshot` and export the mock as `mockQueryOnSnapshotUnsubscribe`.
A typical usage is to test whether the unsubscribe callback is called during your application's lifecycle.
For example, here is a React component that subscribes on mount and unsubscribes on unmount:
```ts
const MyComponent = () => {
useEffect(() => {
const unsubscribe = firestore().collection('test').onSnapshot(() => {
console.log('Got a snapshot');
});
return () => {
unsubscribe();
};
}, []);
return (...);
}
```
We want to test that the component unsubscribes on unmount. Thanks to `mockQueryOnSnapshotUnsubscribe` we can achieve this like this:
```ts
import { mockQueryOnSnapshotUnsubscribe } from 'firestore-jest-mock/mocks/firestore';
describe('MyComponent', () => {
it('should …
```
> Mock the unsubscribe callback returned by onSnapshot 

- src/mocks/firebase.js
Many users will only have the ability to resolve module 'firebase' or 'firebase-admin' but not necessarily both. 
Impacted users see repeated logging of 'Module not found, mocking skipped' messages which can cause concern, and also pollute the logs of larger test suites with many such lines.
This change only logs to console in the more severe case where neither module can be found.
> Reduce 'module not found' console logging

- __tests__/mock-firestore.test.js
- src/mocks/firestore.js
Collection getter methods (`.get()`, `.limit()`, etc) seem to return an empty set of items when collection is created with a string subcollections path. See example below.
This PR introduces a specific condition clause to support the described use case.
```ts
import { FakeFirestore } from 'firestore-jest-mock/mocks/firestore'
import defaultOptions from 'firestore-jest-mock/mocks/helpers/defaultMockOptions'
const firestore = new FakeFirestore({
'subcollection/as/string': [
{ id: '1', name: 'One' },
{ id: '2', name: 'Two' }
]
})
const collection = firestore.collection('subcollection/as/string')
const items = await collection.get()
// items.length === 2
```
> fix: collection getter methods with subcollections path as strings
